name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: dragon-build
      uses: DragonBuild/build@0.0.5
    - name: Uploading Packages
      uses: actions/upload-artifact@v2.2.4
      with:
        name: packages
        path: packages/
